services:
  vespa:
    image: vespaengine/vespa
    hostname: vespa-container
    ports:
      - "8080:8080"
      - "19071:19071"
    deploy:
      resources:
        limits:
          memory: 4G # Adjust memory limits as needed
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ApplicationStatus"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped