services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    restart: unless-stopped
    command: --api=true --api.insecure=true --providers.docker
    ports:
     - "80:80"
     - "4443:443"
     - "8080:8080"
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/traefik.yaml:ro
      - ./shared/:/shared
    networks:
      - traefik
      - budibase_net

networks:
  traefik:
  budibase_net: