services:
  postgres:
    restart: always
    image: pgvector/pgvector:pg17
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      # Postgres DB Super User Password
      # Replace the below with your own secure password & Make sure the password matches the password field in DATABASE_URL above
      - POSTGRES_PASSWORD=postgres

  formbricks:
    restart: always
    image: ghcr.io/formbricks/formbricks:latest
    depends_on:
      - postgres
    ports:
      - ${MAIN_PORT}:3000
    volumes:
      - uploads:/home/nextjs/apps/web/uploads/
      - ./saml-connection:/home/nextjs/apps/web/saml-connection
    environment:
      WEBAPP_URL: ${WEBAPP_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      CRON_SECRET: ${CRON_SECRET}
      EMAIL_VERIFICATION_DISABLED: ${EMAIL_VERIFICATION_DISABLED}
      PASSWORD_RESET_DISABLED: ${PASSWORD_RESET_DISABLED}
      S3_FORCE_PATH_STYLE: ${S3_FORCE_PATH_STYLE}
    labels:
      - traefik.enable=true
      - traefik.http.routers.formbricks.rule=Host(`formbricks.localhost`)
      - "traefik.http.routers.formbricks.entrypoints=websecure"
      - "traefik.http.routers.formbricks.tls.certresolver=lets-encrypt"
      - "traefik.http.services.formbricks.loadbalancer.server.port=${MAIN_PORT}"
volumes:
  postgres:
    driver: local
  uploads:
    driver: local
